# Transformer Pipeline - 100K Dataset

This notebook fine-tunes `BERT` and `DistilBERT` on `processed_data/dataset_100k`.

The execution is split into three parts:

1. Run `BERT` and save its outputs immediately.
2. Run `DistilBERT` and save its outputs immediately.
3. Combine both model summaries into one final comparison table.

- `metrics.json`
- `training_history.csv`
- `classification_report.csv`
- `confusion_matrix.csv`
- `confusion_matrix.png`
- `test_predictions.csv`
- optional attention visualization outputs

The random seed is fixed at `42` to match your team plan.

In [ ]:
import subprocess
subprocess.run(["pip", "install", "sentencepiece"])
subprocess.run(["pip", "uninstall", "torch", "torchvision", "torchaudio", "-y"])

subprocess.run(["pip", "install", "torch", "torchvision", "torchaudio", 
                "--index-url", "https://download.pytorch.org/whl/cu121"])

packages = [
    "pandas",
    "numpy", 
    "transformers",
    "scikit-learn",
    "matplotlib",
    "ipywidgets",
    "transformers-interpret"
]
for pkg in packages:
    subprocess.run(["pip", "install", pkg])

print("All packages installed successfully!")

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting sentencepiece
  Downloading http://mirrors.aliyun.com/pypi/packages/04/88/14f2f4a2b922d8b39be45bf63d79e6cd3a9b2f248b2fcb98a69b12af12f5/sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 9.6 MB/s eta 0:00:00:00:0100:01
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.2.1

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Found existing installation: torch 2.3.0+cu121
Uninstalling torch-2.3.0+cu121:
  Successfully uninstalled torch-2.3.0+cu121
Found existing installation: torchvision 0.18.0+cu121
Uninstalling torchvision-0.18.0+cu121:
  Successfully uninstalled torchvision-0.18.0+cu121

WARNING: Skipping torchaudio as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (780.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 4.4 MB/s eta 0:00:0000:0100:02
Collecting torchvision
  Downloading https://download-r2.pytorch.org/whl/cu121/torchvision-0.20.1%2Bcu121-cp312-cp312-linux_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 2.7 MB/s eta 0:00:0000:0100:010m
Collecting torchaudio
  Downloading https://download-r2.pytorch.org/whl/cu121/torchaudio-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 10.9 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: filelock in /root/miniconda3/lib/python3.12/site-packages (from torch) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /root/miniconda3/lib/python3.12/site-packages (from torch) (4.12.1)
Requirement already satisfied: networkx in /root/miniconda3/lib/python3.12/site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/lib/python3.12/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /root/miniconda3/lib/python3.12/site-packages (from torch) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.105)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 4.4 MB/s eta 0:00:0000:0100:03
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/lib/python3.12/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/lib/python3.12/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/lib/python3.12/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.0.106)
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 7.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch) (12.1.105)
Collecting triton==3.1.0 (from torch)
  Downloading https://download-r2.pytorch.org/whl/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 4.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: setuptools in /root/miniconda3/lib/python3.12/site-packages (from torch) (69.5.1)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.5.40)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /root/miniconda3/lib/python3.12/site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /root/miniconda3/lib/python3.12/site-packages (from torchvision) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/lib/python3.12/site-packages (from jinja2->torch) (2.1.5)
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 3.4 MB/s eta 0:00:00a 0:00:010m
Installing collected packages: triton, sympy, nvidia-nccl-cu12, nvidia-cudnn-cu12, torch, torchvision, torchaudio
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12.1
    Uninstalling sympy-1.12.1:
      Successfully uninstalled sympy-1.12.1
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.20.5
    Uninstalling nvidia-nccl-cu12-2.20.5:
      Successfully uninstalled nvidia-nccl-cu12-2.20.5
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 8.9.2.26
    Uninstalling nvidia-cudnn-cu12-8.9.2.26:
      Successfully uninstalled nvidia-cudnn-cu12-8.9.2.26
Successfully installed nvidia-cudnn-cu12-9.1.0.70 nvidia-nccl-cu12-2.21.5 sympy-1.13.1 torch-2.5.1+cu121 torchaudio-2.5.1+cu121 torchvision-0.20.1+cu121 triton-3.1.0

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting pandas
  Downloading http://mirrors.aliyun.com/pypi/packages/c4/a8/3a61a721472959ab0ce865ef05d10b0d6bfe27ce8801c99f33d4fa996e65/pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 17.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.26.0 in /root/miniconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /root/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pandas
Successfully installed pandas-3.0.2

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: numpy in /root/miniconda3/lib/python3.12/site-packages (1.26.4)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting transformers
  Downloading http://mirrors.aliyun.com/pypi/packages/e7/28/35f7411ff80a3640c1f4fc907dcbb6a65061ebb82f66950e38bfc9f7f740/transformers-5.5.0-py3-none-any.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 25.1 MB/s eta 0:00:0000:010:01
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/73/37/0d15d16150e1829f3e90962c99f28257f6de9e526a680b4c6f5acdb54fd2/huggingface_hub-1.9.0-py3-none-any.whl (637 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 637.4/637.4 kB 63.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/lib/python3.12/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/lib/python3.12/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/lib/python3.12/site-packages (from transformers) (6.0.1)
Collecting regex>=2025.10.22 (from transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/11/0e/a9f6f81013e0deaf559b25711623864970fe6a098314e374ccb1540a4152/regex-2026.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.1/801.1 kB 17.1 MB/s eta 0:00:00a 0:00:01
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/2e/76/932be4b50ef6ccedf9d3c6639b056a967a86258c6d9200643f01269211ca/tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 21.2 MB/s eta 0:00:0000:0100:01
Collecting typer (from transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/4a/91/48db081e7a63bb37284f9fbcefda7c44c277b18b0e13fbc36ea2335b71e6/typer-0.24.1-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 26.0 MB/s eta 0:00:00
Collecting safetensors>=0.4.3 (from transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/a0/60/429e9b1cb3fc651937727befe258ea24122d9663e4d5709a48c9cbfceecb/safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 24.1 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /root/miniconda3/lib/python3.12/site-packages (from transformers) (4.66.2)
Requirement already satisfied: filelock>=3.10.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.5.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/df/9a/a24b26dc8a65f0ecc0fe5be981a19e61e7ca963b85e062c083f3a9100529/hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.8 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: httpx<1,>=0.23.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.27.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Collecting click>=8.2.1 (from typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/e4/20/71885d8b97d4f3dde17b1fdb92dbd4908b00541c5a3379787137285f602e/click-8.3.2-py3-none-any.whl (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.4/108.4 kB 42.7 MB/s eta 0:00:00
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/e0/f9/0595336914c5619e5f28a1fb793285925a8cd4b432c9da0a987836c7f822/shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich>=12.3.0 (from typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/14/25/b208c5683343959b670dc001595f2f3737e051da617f66c31f7c4fa93abc/rich-14.3.3-py3-none-any.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.5/310.5 kB 7.2 MB/s eta 0:00:0000:01
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/1e/d3/26bf1008eb3d2daa8ef4cacc7f3bfdc11818d111f7e2d0201bc6e3b49d45/annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Requirement already satisfied: anyio in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.4.0)
Requirement already satisfied: certifi in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.5)
Requirement already satisfied: idna in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: sniffio in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /root/miniconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.14.0)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/94/54/e7d793b573f298e1c9013b8c4dade17d481164aa517d1d7148619c2cedbf/markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /root/miniconda3/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers) (2.18.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers)
  Downloading http://mirrors.aliyun.com/pypi/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: shellingham, safetensors, regex, mdurl, hf-xet, click, annotated-doc, markdown-it-py, rich, typer, huggingface-hub, tokenizers, transformers
Successfully installed annotated-doc-0.0.4 click-8.3.2 hf-xet-1.4.3 huggingface-hub-1.9.0 markdown-it-py-4.0.0 mdurl-0.1.2 regex-2026.4.4 rich-14.3.3 safetensors-0.7.0 shellingham-1.5.4 tokenizers-0.22.2 transformers-5.5.0 typer-0.24.1

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting scikit-learn
  Downloading http://mirrors.aliyun.com/pypi/packages/97/74/b7a304feb2b49df9fafa9382d4d09061a96ee9a9449a7cbea7988dda0828/scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 18.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.24.1 in /root/miniconda3/lib/python3.12/site-packages (from scikit-learn) (1.26.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading http://mirrors.aliyun.com/pypi/packages/01/8e/1e35281b8ab6d5d72ebe9911edcdffa3f36b04ed9d51dec6dd140396e220/scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 10.1 MB/s eta 0:00:0000:0100:01
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/91/984aca2ec129e2757d1e4e3c81c3fcda9d0f85b74670a094cc443d9ee949/joblib-1.5.3-py3-none-any.whl (309 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 4.9 MB/s eta 0:00:0000:01
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading http://mirrors.aliyun.com/pypi/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: matplotlib in /root/miniconda3/lib/python3.12/site-packages (3.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /root/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: ipywidgets in /root/miniconda3/lib/python3.12/site-packages (8.1.3)
Requirement already satisfied: comm>=0.1.3 in /root/miniconda3/lib/python3.12/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /root/miniconda3/lib/python3.12/site-packages (from ipywidgets) (8.25.0)
Requirement already satisfied: traitlets>=4.3.1 in /root/miniconda3/lib/python3.12/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.11 in /root/miniconda3/lib/python3.12/site-packages (from ipywidgets) (4.0.11)
Requirement already satisfied: jupyterlab-widgets~=3.0.11 in /root/miniconda3/lib/python3.12/site-packages (from ipywidgets) (3.0.11)
Requirement already satisfied: decorator in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.45)
Requirement already satisfied: pygments>=2.4.0 in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /root/miniconda3/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /root/miniconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /root/miniconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /root/miniconda3/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /root/miniconda3/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /root/miniconda3/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /root/miniconda3/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /root/miniconda3/lib/python3.12/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting transformers-interpret
  Downloading http://mirrors.aliyun.com/pypi/packages/a8/4c/19098012fa903e9cea195fc381db0504f73fe3fcf9ccf4338f4b2b157092/transformers_interpret-0.10.0-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 1.5 MB/s eta 0:00:00
Collecting captum>=0.3.1 (from transformers-interpret)
  Downloading http://mirrors.aliyun.com/pypi/packages/7d/2d/57138b29a53d1fd267c8093989f6ec64ef55d3c6bd336fac475239c61b97/captum-0.8.0-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 3.9 MB/s eta 0:00:00a 0:00:010m
Collecting ipython<8.0.0,>=7.31.1 (from transformers-interpret)
  Downloading http://mirrors.aliyun.com/pypi/packages/7c/6a/1f1365f4bf9fcb349fcaa5b61edfcefa721aa13ff37c5631296b12fab8e5/ipython-7.34.0-py3-none-any.whl (793 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.8/793.8 kB 7.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: transformers>=3.0.0 in /root/miniconda3/lib/python3.12/site-packages (from transformers-interpret) (5.5.0)
Requirement already satisfied: matplotlib in /root/miniconda3/lib/python3.12/site-packages (from captum>=0.3.1->transformers-interpret) (3.9.0)
Requirement already satisfied: numpy<2.0 in /root/miniconda3/lib/python3.12/site-packages (from captum>=0.3.1->transformers-interpret) (1.26.4)
Requirement already satisfied: packaging in /root/miniconda3/lib/python3.12/site-packages (from captum>=0.3.1->transformers-interpret) (23.2)
Requirement already satisfied: torch>=1.10 in /root/miniconda3/lib/python3.12/site-packages (from captum>=0.3.1->transformers-interpret) (2.5.1+cu121)
Requirement already satisfied: tqdm in /root/miniconda3/lib/python3.12/site-packages (from captum>=0.3.1->transformers-interpret) (4.66.2)
Requirement already satisfied: setuptools>=18.5 in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (69.5.1)
Requirement already satisfied: jedi>=0.16 in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (0.19.1)
Requirement already satisfied: decorator in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (5.1.1)
Collecting pickleshare (from ipython<8.0.0,>=7.31.1->transformers-interpret)
  Downloading http://mirrors.aliyun.com/pypi/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Requirement already satisfied: traitlets>=4.2 in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (5.14.3)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (3.0.45)
Requirement already satisfied: pygments in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (2.18.0)
Collecting backcall (from ipython<8.0.0,>=7.31.1->transformers-interpret)
  Downloading http://mirrors.aliyun.com/pypi/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: matplotlib-inline in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /root/miniconda3/lib/python3.12/site-packages (from ipython<8.0.0,>=7.31.1->transformers-interpret) (4.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (1.9.0)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (0.22.2)
Requirement already satisfied: typer in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /root/miniconda3/lib/python3.12/site-packages (from transformers>=3.0.0->transformers-interpret) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (3.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (2024.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (0.27.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /root/miniconda3/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (4.12.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /root/miniconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython<8.0.0,>=7.31.1->transformers-interpret) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /root/miniconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython<8.0.0,>=7.31.1->transformers-interpret) (0.7.0)
Requirement already satisfied: wcwidth in /root/miniconda3/lib/python3.12/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<8.0.0,>=7.31.1->transformers-interpret) (0.2.13)
Requirement already satisfied: networkx in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /root/miniconda3/lib/python3.12/site-packages (from torch>=1.10->captum>=0.3.1->transformers-interpret) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10->captum>=0.3.1->transformers-interpret) (12.5.40)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.10->captum>=0.3.1->transformers-interpret) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (1.4.5)
Requirement already satisfied: pillow>=8 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /root/miniconda3/lib/python3.12/site-packages (from matplotlib->captum>=0.3.1->transformers-interpret) (2.9.0.post0)
Requirement already satisfied: click>=8.2.1 in /root/miniconda3/lib/python3.12/site-packages (from typer->transformers>=3.0.0->transformers-interpret) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /root/miniconda3/lib/python3.12/site-packages (from typer->transformers>=3.0.0->transformers-interpret) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /root/miniconda3/lib/python3.12/site-packages (from typer->transformers>=3.0.0->transformers-interpret) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /root/miniconda3/lib/python3.12/site-packages (from typer->transformers>=3.0.0->transformers-interpret) (0.0.4)
Requirement already satisfied: anyio in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (4.4.0)
Requirement already satisfied: certifi in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (1.0.5)
Requirement already satisfied: idna in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (3.7)
Requirement already satisfied: sniffio in /root/miniconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /root/miniconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->transformers-interpret) (0.14.0)
Requirement already satisfied: six>=1.5 in /root/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib->captum>=0.3.1->transformers-interpret) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /root/miniconda3/lib/python3.12/site-packages (from rich>=12.3.0->typer->transformers>=3.0.0->transformers-interpret) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/lib/python3.12/site-packages (from jinja2->torch>=1.10->captum>=0.3.1->transformers-interpret) (2.1.5)
Requirement already satisfied: mdurl~=0.1 in /root/miniconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers>=3.0.0->transformers-interpret) (0.1.2)
Installing collected packages: pickleshare, backcall, ipython, captum, transformers-interpret
  Attempting uninstall: ipython
    Found existing installation: ipython 8.25.0
    Uninstalling ipython-8.25.0:
      Successfully uninstalled ipython-8.25.0
Successfully installed backcall-0.2.0 captum-0.8.0 ipython-7.34.0 pickleshare-0.7.5 transformers-interpret-0.10.0
All packages installed successfully!

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [1]:
from pathlib import Path
PROJECT_ROOT = Path("/root/autodl-tmp")
DATASET_NAME = "dataset_100k"
DATASET_DIR = Path("processed_data") / DATASET_NAME
OUTPUT_ROOT = Path("member_c_outputs")
BERT_MODEL_KEY = "bert"
DISTILBERT_MODEL_KEY = "distilbert"
EPOCHS = 3
BATCH_SIZE = 8
MAX_LENGTH = 256
LEARNING_RATE = 2e-5
SEED = 42
ATTENTION_SAMPLES = 3
SKIP_ATTENTION = False
DATASET_DIR

PosixPath('processed_data/dataset_100k')

In [2]:
import json
import os
import random
import time
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", str((Path.cwd() / ".matplotlib_cache").resolve()))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import ConfusionMatrixDisplay, accuracy_score, classification_report, confusion_matrix, f1_score
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer, get_linear_schedule_with_warmup

LABEL_NAMES = {0: "Human", 1: "AI"}
MODEL_MAP = {
    "bert": "/root/autodl-tmp/bert-base-uncased",
    "distilbert": "/root/autodl-tmp/distilbert-base-uncased",
}


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def read_split(csv_path: Path) -> pd.DataFrame:
    dataframe = pd.read_csv(csv_path)
    required_columns = {"text", "generated"}
    missing_columns = required_columns.difference(dataframe.columns)
    if missing_columns:
        raise ValueError(f"{csv_path} is missing columns: {sorted(missing_columns)}")
    dataframe = dataframe.dropna(subset=["text", "generated"]).copy()
    dataframe["text"] = dataframe["text"].astype(str)
    dataframe["generated"] = dataframe["generated"].astype(int)
    return dataframe.reset_index(drop=True)


class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length):
        self.texts = list(texts)
        self.labels = list(labels)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        text = self.texts[index]
        label = self.labels[index]
        encoding = self.tokenizer(
            text,
            add_special_tokens=True,
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_attention_mask=True,
            return_tensors="pt",
        )
        return {
            "input_ids": encoding["input_ids"].flatten(),
            "attention_mask": encoding["attention_mask"].flatten(),
            "labels": torch.tensor(label, dtype=torch.long),
        }


def create_data_loader(dataframe, tokenizer, max_length, batch_size, shuffle, device):
    dataset = TextClassificationDataset(
        texts=dataframe["text"].tolist(),
        labels=dataframe["generated"].tolist(),
        tokenizer=tokenizer,
        max_length=max_length,
    )
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=0,
        pin_memory=device.type == "cuda",
    )


def train_epoch(model, data_loader, optimizer, scheduler, device):
    model.train()
    losses = []
    predictions = []
    true_labels = []

    for batch in data_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits
        preds = torch.argmax(logits, dim=1)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

        losses.append(loss.item())
        predictions.extend(preds.detach().cpu().tolist())
        true_labels.extend(labels.detach().cpu().tolist())

    return {
        "loss": float(np.mean(losses)) if losses else 0.0,
        "accuracy": accuracy_score(true_labels, predictions),
        "macro_f1": f1_score(true_labels, predictions, average="macro", zero_division=0),
    }


def evaluate_model(model, data_loader, device):
    model.eval()
    losses = []
    predictions = []
    true_labels = []

    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            logits = outputs.logits
            preds = torch.argmax(logits, dim=1)

            losses.append(loss.item())
            predictions.extend(preds.detach().cpu().tolist())
            true_labels.extend(labels.detach().cpu().tolist())

    return {
        "loss": float(np.mean(losses)) if losses else 0.0,
        "accuracy": accuracy_score(true_labels, predictions),
        "macro_f1": f1_score(true_labels, predictions, average="macro", zero_division=0),
        "predictions": predictions,
        "true_labels": true_labels,
    }


def save_confusion_outputs(y_true, y_pred, output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)
    class_order = sorted(LABEL_NAMES)
    display_labels = [LABEL_NAMES[label_id] for label_id in class_order]
    matrix = confusion_matrix(y_true, y_pred, labels=class_order)
    pd.DataFrame(matrix, index=display_labels, columns=display_labels).to_csv(output_dir / "confusion_matrix.csv")

    figure, axis = plt.subplots(figsize=(6, 6))
    ConfusionMatrixDisplay(confusion_matrix=matrix, display_labels=display_labels).plot(
        ax=axis,
        cmap="Blues",
        colorbar=False,
    )
    figure.tight_layout()
    figure.savefig(output_dir / "confusion_matrix.png", dpi=200, bbox_inches="tight")
    plt.close(figure)


def save_attention_visualizations(model, tokenizer, predictions_dataframe, output_dir, sample_count):
    output_dir.mkdir(parents=True, exist_ok=True)
    status_file = output_dir / "attention_visualization_status.txt"

    try:
        from transformers_interpret import SequenceClassificationExplainer
    except Exception as exc:
        status_file.write_text(
            "Skipped attention visualization because transformers-interpret is not available.\n"
            "Install with: pip install transformers-interpret\n"
            f"Original import error: {exc}\n",
            encoding="utf-8",
        )
        return

    sample_dataframe = predictions_dataframe.copy()
    sample_dataframe["correct"] = sample_dataframe["generated"] == sample_dataframe["prediction"]
    sample_dataframe = sample_dataframe.sort_values(by=["correct", "text"], ascending=[True, True]).head(sample_count)

    if sample_dataframe.empty:
        status_file.write_text("No samples available for attention visualization.\n", encoding="utf-8")
        return

    explainer = SequenceClassificationExplainer(model, tokenizer)
    summary_lines = []

    for sample_index, row in enumerate(sample_dataframe.itertuples(index=False), start=1):
        text = str(row.text)
        tokens = tokenizer.encode(text)
        if len(tokens) > 510:
            tokens = tokens[:510]
            text = tokenizer.decode(tokens, skip_special_tokens=True)
        attributions = explainer(text)
        attribution_dataframe = pd.DataFrame(attributions, columns=["token", "attribution"])
        attribution_dataframe = attribution_dataframe[attribution_dataframe["token"].astype(str).str.strip().ne("")].copy()
        attribution_dataframe["abs_attribution"] = attribution_dataframe["attribution"].abs()
        attribution_dataframe.to_csv(output_dir / f"sample_{sample_index:02d}_token_attributions.csv", index=False)

        top_tokens = attribution_dataframe.nlargest(12, "abs_attribution").iloc[::-1]
        figure, axis = plt.subplots(figsize=(10, 5))
        axis.barh(top_tokens["token"], top_tokens["attribution"], color="#3b82f6")
        axis.set_title(
            f"Sample {sample_index}: true={LABEL_NAMES[int(row.generated)]}, pred={LABEL_NAMES[int(row.prediction)]}"
        )
        axis.set_xlabel("Token attribution")
        figure.tight_layout()
        figure.savefig(output_dir / f"sample_{sample_index:02d}_top_tokens.png", dpi=200, bbox_inches="tight")
        plt.close(figure)

        top_token_text = ", ".join(top_tokens["token"].astype(str).tolist())
        summary_lines.append(
            f"sample_{sample_index:02d}: true={LABEL_NAMES[int(row.generated)]}, pred={LABEL_NAMES[int(row.prediction)]}, top_tokens=[{top_token_text}]"
        )

    status_file.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")


def sanitize_model_name(model_name):
    return model_name.replace("/", "_").replace("-", "_")


def run_single_model(dataset_name, dataset_dir, output_root, model_key, epochs, batch_size, max_length, learning_rate, seed, attention_samples, skip_attention):
    set_seed(seed)
    device = get_device()
    model_name = MODEL_MAP[model_key]
    model_slug = sanitize_model_name(model_name)
    model_output_dir = output_root / dataset_name / model_slug
    model_output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Dataset: {dataset_name} | Model: {model_name} ===")
    print(f"Using device: {device}")

    train_dataframe = read_split(dataset_dir / "train.csv")
    validation_dataframe = read_split(dataset_dir / "validation.csv")
    test_dataframe = read_split(dataset_dir / "test.csv")

    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2,
        id2label=LABEL_NAMES,
        label2id={label_name: label_id for label_id, label_name in LABEL_NAMES.items()},
    ).to(device)

    train_loader = create_data_loader(train_dataframe, tokenizer, max_length, batch_size, True, device)
    validation_loader = create_data_loader(validation_dataframe, tokenizer, max_length, batch_size, False, device)
    test_loader = create_data_loader(test_dataframe, tokenizer, max_length, batch_size, False, device)

    optimizer = AdamW(model.parameters(), lr=learning_rate)
    total_training_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=0,
        num_training_steps=total_training_steps,
    )

    training_history = []
    best_validation_f1 = -1.0
    best_model_dir = model_output_dir / "best_model"

    start_time = time.perf_counter()
    for epoch_index in range(1, epochs + 1):
        train_metrics = train_epoch(model, train_loader, optimizer, scheduler, device)
        validation_metrics = evaluate_model(model, validation_loader, device)

        epoch_metrics = {
            "epoch": epoch_index,
            "train_loss": train_metrics["loss"],
            "train_accuracy": train_metrics["accuracy"],
            "train_macro_f1": train_metrics["macro_f1"],
            "val_loss": validation_metrics["loss"],
            "val_accuracy": validation_metrics["accuracy"],
            "val_macro_f1": validation_metrics["macro_f1"],
        }
        training_history.append(epoch_metrics)

        print(
            f"Epoch {epoch_index}/{epochs} | "
            f"train_loss={epoch_metrics['train_loss']:.4f} | "
            f"train_acc={epoch_metrics['train_accuracy']:.4f} | "
            f"val_loss={epoch_metrics['val_loss']:.4f} | "
            f"val_macro_f1={epoch_metrics['val_macro_f1']:.4f}"
        )

        if validation_metrics["macro_f1"] > best_validation_f1:
            best_validation_f1 = float(validation_metrics["macro_f1"])
            model.save_pretrained(best_model_dir)
            tokenizer.save_pretrained(best_model_dir)

    training_seconds = time.perf_counter() - start_time
    pd.DataFrame(training_history).to_csv(model_output_dir / "training_history.csv", index=False)

    best_model = AutoModelForSequenceClassification.from_pretrained(best_model_dir).to(device)
    test_metrics = evaluate_model(best_model, test_loader, device)
    y_true = list(test_metrics["true_labels"])
    y_pred = list(test_metrics["predictions"])

    report_dataframe = pd.DataFrame(
        classification_report(
            y_true,
            y_pred,
            labels=sorted(LABEL_NAMES),
            target_names=[LABEL_NAMES[label_id] for label_id in sorted(LABEL_NAMES)],
            output_dict=True,
            zero_division=0,
        )
    ).transpose()
    report_dataframe.to_csv(model_output_dir / "classification_report.csv")

    predictions_dataframe = test_dataframe.copy()
    predictions_dataframe["prediction"] = y_pred
    predictions_dataframe["true_label"] = predictions_dataframe["generated"].map(LABEL_NAMES)
    predictions_dataframe["predicted_label"] = predictions_dataframe["prediction"].map(LABEL_NAMES)
    predictions_dataframe["is_correct"] = predictions_dataframe["generated"] == predictions_dataframe["prediction"]
    predictions_dataframe.to_csv(model_output_dir / "test_predictions.csv", index=False)

    save_confusion_outputs(y_true, y_pred, model_output_dir)

    if skip_attention:
        (model_output_dir / "attention_visualization_status.txt").write_text(
            "Skipped attention visualization because SKIP_ATTENTION is True.\n",
            encoding="utf-8",
        )
    else:
        save_attention_visualizations(
            model=best_model,
            tokenizer=tokenizer,
            predictions_dataframe=predictions_dataframe,
            output_dir=model_output_dir / "attention_visualizations",
            sample_count=attention_samples,
        )

    summary = {
        "dataset": dataset_name,
        "dataset_dir": str(dataset_dir),
        "model_key": model_key,
        "model_name": model_name,
        "device": str(device),
        "seed": seed,
        "epochs": epochs,
        "batch_size": batch_size,
        "max_length": max_length,
        "learning_rate": learning_rate,
        "training_seconds": round(training_seconds, 4),
        "test_loss": round(float(test_metrics["loss"]), 6),
        "test_accuracy": round(float(test_metrics["accuracy"]), 6),
        "test_macro_f1": round(float(test_metrics["macro_f1"]), 6),
    }

    with (model_output_dir / "metrics.json").open("w", encoding="utf-8") as output_file:
        json.dump(summary, output_file, indent=2)

    print(
        f"Finished {dataset_name} / {model_name} | "
        f"test_accuracy={summary['test_accuracy']:.4f} | "
        f"test_macro_f1={summary['test_macro_f1']:.4f}"
    )

    return summary


def run_all_models(dataset_name, dataset_dir, output_root, models, epochs, batch_size, max_length, learning_rate, seed, attention_samples, skip_attention):
    summaries = []
    for model_key in models:
        summaries.append(
            run_single_model(
                dataset_name=dataset_name,
                dataset_dir=dataset_dir,
                output_root=output_root,
                model_key=model_key,
                epochs=epochs,
                batch_size=batch_size,
                max_length=max_length,
                learning_rate=learning_rate,
                seed=seed,
                attention_samples=attention_samples,
                skip_attention=skip_attention,
            )
        )
    return pd.DataFrame(summaries)

## Part 1 - Run BERT

Run this cell first if you want the `BERT` result immediately.

In [4]:
bert_result = run_single_model(
    dataset_name=DATASET_NAME,
    dataset_dir=DATASET_DIR,
    output_root=OUTPUT_ROOT,
    model_key=BERT_MODEL_KEY,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    max_length=MAX_LENGTH,
    learning_rate=LEARNING_RATE,
    seed=SEED,
    attention_samples=ATTENTION_SAMPLES,
    skip_attention=SKIP_ATTENTION,
)

bert_result_df = pd.DataFrame([bert_result])
bert_result_df

=== Dataset: dataset_100k | Model: /root/autodl-tmp/bert-base-uncased ===
Using device: cuda

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: /root/autodl-tmp/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Epoch 1/3 | train_loss=0.0492 | train_acc=0.9891 | val_loss=0.0425 | val_macro_f1=0.9933

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 2/3 | train_loss=0.0123 | train_acc=0.9977 | val_loss=0.0164 | val_macro_f1=0.9969

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 3/3 | train_loss=0.0027 | train_acc=0.9995 | val_loss=0.0228 | val_macro_f1=0.9963

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (566 > 512). Running this sequence through the model will result in indexing errors

Finished dataset_100k / /root/autodl-tmp/bert-base-uncased | test_accuracy=0.9978 | test_macro_f1=0.9978

,dataset,dataset_dir,model_key,model_name,device,seed,epochs,batch_size,max_length,learning_rate,training_seconds,test_loss,test_accuracy,test_macro_f1
0,dataset_100k,processed_data/dataset_100k,bert,/root/autodl-tmp/bert-base-uncased,cuda,42,3,8,256,0.00002,2153.9359,0.013189,0.9978,0.9978

## Part 2 - Run DistilBERT

Run this cell after `BERT`. It will save the `DistilBERT` outputs independently.

In [3]:
distilbert_result = run_single_model(
    dataset_name=DATASET_NAME,
    dataset_dir=DATASET_DIR,
    output_root=OUTPUT_ROOT,
    model_key=DISTILBERT_MODEL_KEY,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    max_length=MAX_LENGTH,
    learning_rate=LEARNING_RATE,
    seed=SEED,
    attention_samples=ATTENTION_SAMPLES,
    skip_attention=SKIP_ATTENTION,
)

distilbert_result_df = pd.DataFrame([distilbert_result])
distilbert_result_df

=== Dataset: dataset_100k | Model: /root/autodl-tmp/distilbert-base-uncased ===
Using device: cuda

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: /root/autodl-tmp/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Epoch 1/3 | train_loss=0.0549 | train_acc=0.9866 | val_loss=0.0454 | val_macro_f1=0.9920

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 2/3 | train_loss=0.0132 | train_acc=0.9974 | val_loss=0.0122 | val_macro_f1=0.9971

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 3/3 | train_loss=0.0030 | train_acc=0.9994 | val_loss=0.0154 | val_macro_f1=0.9976

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Finished dataset_100k / /root/autodl-tmp/distilbert-base-uncased | test_accuracy=0.9975 | test_macro_f1=0.9975

,dataset,dataset_dir,model_key,model_name,device,seed,epochs,batch_size,max_length,learning_rate,training_seconds,test_loss,test_accuracy,test_macro_f1
0,dataset_100k,processed_data/dataset_100k,distilbert,/root/autodl-tmp/distilbert-base-uncased,cuda,42,3,8,256,0.00002,1353.5298,0.015469,0.9975,0.9975

## Part 3 - Final Summary

Run this cell after both models finish to get one combined comparison table.

In [4]:
summary_rows = []

if 'bert_result' in globals():
    summary_rows.append(bert_result)

if 'distilbert_result' in globals():
    summary_rows.append(distilbert_result)

if not summary_rows:
    raise ValueError('No model results found yet. Run the BERT and/or DistilBERT cells first.')

final_results_df = pd.DataFrame(summary_rows)
final_results_df = final_results_df.sort_values(by='model_name').reset_index(drop=True)
final_results_df.to_csv(OUTPUT_ROOT / DATASET_NAME / 'combined_model_summary.csv', index=False)
final_results_df

,dataset,dataset_dir,model_key,model_name,device,seed,epochs,batch_size,max_length,learning_rate,training_seconds,test_loss,test_accuracy,test_macro_f1
0,dataset_100k,processed_data/dataset_100k,distilbert,/root/autodl-tmp/distilbert-base-uncased,cuda,42,3,8,256,0.00002,1353.5298,0.015469,0.9975,0.9975